# 生产环境配置文件
name = "augtoken-manager"
main = "src/index.ts"
compatibility_date = "2025-09-20"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
# 用户凭据，格式: 用户名:密码 (User credentials, format: username:password)
USER_CREDENTIALS = "well:wellgone"
#lwg-lawyer.com welldone.ggff.net well.edu.kg wellgone.cn
# CloudMail邮箱服务配置 (CloudMail email service configuration) - 可选
# 可用的邮箱域名列表 (Available email domains)
EMAIL_DOMAINS = ["lwg-lawyer.com","welldone.ggff.net","well.edu.kg","ellgone.cn"]
# 您的CloudMail部署基础URL (Your CloudMail deployment base URL)
EMAIL_API_BASE_URL = "https://mail.wellgone.cn/"
# CloudMail管理员令牌 (CloudMail admin token)
EMAIL_API_TOKEN = ""

# KV存储命名空间配置 (KV Storage Namespaces)

# Token记录存储 (Token records storage)
# [[kv_namespaces]]
# binding = "TOKENS_KV"
# id = ""

# 会话和临时数据存储 (Session and temporary data storage)
# 包含：用户会话、OAuth状态、速率限制数据
# [[kv_namespaces]]
# binding = "SESSIONS_KV"
# id = ""